#==============================================================#
# 0650 pg_subrel
#==============================================================#
pg_subrel:
  name: pg_subrel
  desc: PostgreSQL subscripted relation group by state
  query: SELECT CURRENT_CATALOG AS datname, ss.subname, sr.srsubstate::TEXT AS state, count(*) AS count FROM pg_catalog.pg_subscription_rel AS sr JOIN (SELECT DISTINCT subid, subname FROM pg_catalog.pg_stat_subscription) AS ss ON ss.subid = sr.srsubid GROUP BY ss.subname, sr.srsubstate;
  ttl: 10
  min_version: 100000
  metrics:
    - datname:              { usage: LABEL  ,description: "Name of the database which publication belonged" }
    - subname:              { usage: LABEL  ,description: "Name of the subscription" }
    - state:                { usage: LABEL  ,description: "State of table in subscription, i=initialize, d=data copy, s=sync, r=ready" }
    - count:                { usage: GAUGE  ,description: "Count of relation in this subscription and corresponding state" }


